### ISSUE TITLE
使用biliproapi-1:latest时出现问题

### ISSUE THREAD

**Issue by Eoniva616** [cyril2007/biliproapi-1#1]
网页返回 Internal Server Error

docker logs 提示 
:~# docker logs 52cb9d37064b
API is listening on port 23233
extractBVandP:null
开始新判断
1
https://www.bilibili.com/video/BV1ii421k7sP
TypeError: Cannot read properties of undefined (reading '0')
    at getVideoLink (/app/bilipro.js:55:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cyril2007** [comment]
因为识别是通过Bv开始至？或者/截止，你试一下https://bili.hextiger.fun/biliapi?url=https://www.bilibili.com/video/BV1ii421k7sP/
